<a href="https://colab.research.google.com/github/SnigdhaPanakanti/Snigdha_DATA690/blob/main/Assignment_05/Part_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment - 05**

## PART - 04:  Intro to NumPy

### **Numpy: Numeric computing library**

- NumPy (Numerical Python) is one of the core packages for numerical computing in Python. 
- Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

- NumPy major contributions are:

   - Efficient numeric computation with C primitives
   - Efficient collections with vectorized operations
   - An integrated and natural Linear Algebra API
   - A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

In [1]:
import sys
import numpy as np

### Basic NumPy Arrays:

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Array Types:

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a': 1}, sys])

In [24]:
d.dtype

dtype('O')

### Dimensions and Shapes:

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
A.shape

(2, 3)

In [27]:
A.ndim

2

In [28]:
A.size

6

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

In [34]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [35]:
C.dtype

dtype('O')

In [36]:
C.shape

(2,)

In [37]:
C.size

2

In [38]:
type(C[0])

list

### Indexing and Slicing of Matrices:

In [39]:
#Square Matrix

A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])


In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [44]:
A[1, 0]

4

In [45]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [48]:
A[:2, 2:]

array([[3],
       [6]])

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
A[1] = np.array([10, 10, 10])

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [52]:
A[2] = 99

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics:

In [54]:
a = np.array([1, 2, 3, 4])

In [55]:
a.sum()

10

In [56]:
a.mean()

2.5

In [57]:
a.std()

1.118033988749895

In [58]:
a.var()

1.25

In [59]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [60]:
A.sum()

45

In [61]:
A.mean()

5.0

In [62]:
A.var()

6.666666666666667

In [63]:
A.std()

2.581988897471611

In [64]:
A.sum(axis=0)

array([12, 15, 18])

In [65]:
A.sum(axis=1)

array([ 6, 15, 24])

In [66]:
A.mean(axis=0)

array([4., 5., 6.])

In [67]:
A.mean(axis=1)

array([2., 5., 8.])

In [68]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [69]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Broadcasting and Vectorized operations:

In [70]:
a = np.arange(4)

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a + 10

array([10, 11, 12, 13])

In [73]:
a * 10

array([ 0, 10, 20, 30])

In [74]:
a

array([0, 1, 2, 3])

In [75]:
a += 100

In [76]:
a

array([100, 101, 102, 103])

In [77]:
l = [0,1,2,3]

In [78]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [79]:
a = np.arange(4)

In [80]:
a

array([0, 1, 2, 3])

In [81]:
b = np.array([10, 10, 10, 10])

In [82]:
b

array([10, 10, 10, 10])

In [83]:
a+b

array([10, 11, 12, 13])

In [84]:
a*b

array([ 0, 10, 20, 30])

### Boolean arrays: (Masks)

In [85]:
a = np.arange(4)

In [86]:
a

array([0, 1, 2, 3])

In [87]:
a[0], a[-1]

(0, 3)

In [88]:
a[[0, -1]]

array([0, 3])

In [89]:
a[[True, False, False, True]]

array([0, 3])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a >= 2

array([False, False,  True,  True])

In [92]:
a[a >= 2]

array([2, 3])

In [93]:
a.mean()

1.5

In [94]:
a[a > a.mean()]

array([2, 3])

In [95]:
a[~(a > a.mean())]

array([0, 1])

In [96]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [97]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [98]:
A = np.random.randint(100, size=(3, 3))

In [99]:
A

array([[28, 87, 65],
       [15, 76, 64],
       [81, 21, 32]])

In [100]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([28, 65, 76, 81, 32])

In [101]:
A>30

array([[False,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [102]:
A[A>30]

array([87, 65, 76, 64, 81, 32])

### Linear Algebra:

In [103]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [104]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [105]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [106]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [107]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [108]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Size of objects in Memory


- Int, Floats

In [110]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [111]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [112]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [113]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [114]:
np.dtype(float).itemsize

8

- Lists are even Larger

In [115]:
# A one-element list
sys.getsizeof([1])

80

In [116]:
# An array of one element in numpy
np.array([1]).nbytes

8

- Performance is also important

In [117]:
l = list(range(100000))

In [119]:
a = np.arange(100000)

In [120]:
%time np.sum(a ** 2)

CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 741 µs


333328333350000

In [121]:
%time sum([x ** 2 for x in l])

CPU times: user 32.6 ms, sys: 5.92 ms, total: 38.5 ms
Wall time: 41.3 ms


333328333350000

### Useful Numpy functions


- Random

In [122]:
np.random.random(size=2)

array([0.46109162, 0.11177492])

In [123]:
np.random.normal(size=2)

array([-0.79189237,  0.15640025])

In [124]:
np.random.rand(2, 4)

array([[0.58699356, 0.21724584, 0.92935015, 0.67161719],
       [0.1863437 , 0.71733168, 0.95321881, 0.1960997 ]])

- Arrange

In [125]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [127]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

- Reshape

In [128]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [129]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- Linspace

In [130]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [131]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [132]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

- Zeros, Ones, Empty

In [133]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [134]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [136]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [137]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [138]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [139]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

- identity and eye

In [140]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [141]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [145]:
"Hello World"[6]

'W'